title: "JoeCMath"
description: "Clear math tutorials"
baseurl: ""        # leave empty for root domain (like joecmath.com)
url: "https://joecmath.com"   # your domain

# GitHub Pages supported plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title/
