# _config.yml
title: "JoeCMath"
description: "Clear, quick math tutorials."
url: "https://joecmath.com"   # my domain
baseurl: ""                    # keep empty when using a root domain

# Pretty, nested URLs from post categories
permalink: /:categories/:title/

# Markdown + math-friendly defaults
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax        

# Time / build behavior
timezone: America/New_York
future: false
lsi: false

# Plugins supported on GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # Optional pagination (enable only if you'll use it on /blog/)
  # - jekyll-paginate

# Optional pagination settings (only used if jekyll-paginate is enabled)
# paginate: 8
# paginate_path: "/blog/page:num/"

# Default front matter (so every post gets a layout automatically)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      # Add common tags or author here if you want:
      # author: "JoeCMath"

# Paths to ignore in the build (adjust as needed)
exclude:
  - README.md
  - assets/readme.txt
